# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/anastasia/Рабочий стол/sdr"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/anastasia/Рабочий стол/sdr"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/anastasia/Рабочий стол/sdr/CMakeFiles" "/home/anastasia/Рабочий стол/sdr//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/anastasia/Рабочий стол/sdr/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named implot

# Build rule for target.
implot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 implot
.PHONY : implot

# fast build rule for target.
implot/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/implot.dir/build.make CMakeFiles/implot.dir/build
.PHONY : implot/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/f.o: src/f.cpp.o
.PHONY : src/f.o

# target to build an object file
src/f.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/f.cpp.o
.PHONY : src/f.cpp.o

src/f.i: src/f.cpp.i
.PHONY : src/f.i

# target to preprocess a source file
src/f.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/f.cpp.i
.PHONY : src/f.cpp.i

src/f.s: src/f.cpp.s
.PHONY : src/f.s

# target to generate assembly for a file
src/f.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/f.cpp.s
.PHONY : src/f.cpp.s

src/gui.o: src/gui.cpp.o
.PHONY : src/gui.o

# target to build an object file
src/gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/gui.cpp.o
.PHONY : src/gui.cpp.o

src/gui.i: src/gui.cpp.i
.PHONY : src/gui.i

# target to preprocess a source file
src/gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/gui.cpp.i
.PHONY : src/gui.cpp.i

src/gui.s: src/gui.cpp.s
.PHONY : src/gui.s

# target to generate assembly for a file
src/gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/gui.cpp.s
.PHONY : src/gui.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mapper.o: src/mapper.cpp.o
.PHONY : src/mapper.o

# target to build an object file
src/mapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/mapper.cpp.o
.PHONY : src/mapper.cpp.o

src/mapper.i: src/mapper.cpp.i
.PHONY : src/mapper.i

# target to preprocess a source file
src/mapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/mapper.cpp.i
.PHONY : src/mapper.cpp.i

src/mapper.s: src/mapper.cpp.s
.PHONY : src/mapper.s

# target to generate assembly for a file
src/mapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/mapper.cpp.s
.PHONY : src/mapper.cpp.s

src/rx.o: src/rx.cpp.o
.PHONY : src/rx.o

# target to build an object file
src/rx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/rx.cpp.o
.PHONY : src/rx.cpp.o

src/rx.i: src/rx.cpp.i
.PHONY : src/rx.i

# target to preprocess a source file
src/rx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/rx.cpp.i
.PHONY : src/rx.cpp.i

src/rx.s: src/rx.cpp.s
.PHONY : src/rx.s

# target to generate assembly for a file
src/rx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/rx.cpp.s
.PHONY : src/rx.cpp.s

src/tx.o: src/tx.cpp.o
.PHONY : src/tx.o

# target to build an object file
src/tx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/tx.cpp.o
.PHONY : src/tx.cpp.o

src/tx.i: src/tx.cpp.i
.PHONY : src/tx.i

# target to preprocess a source file
src/tx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/tx.cpp.i
.PHONY : src/tx.cpp.i

src/tx.s: src/tx.cpp.s
.PHONY : src/tx.s

# target to generate assembly for a file
src/tx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/tx.cpp.s
.PHONY : src/tx.cpp.s

third_party/imgui/backends/imgui_impl_opengl3.o: third_party/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : third_party/imgui/backends/imgui_impl_opengl3.o

# target to build an object file
third_party/imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : third_party/imgui/backends/imgui_impl_opengl3.cpp.o

third_party/imgui/backends/imgui_impl_opengl3.i: third_party/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : third_party/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
third_party/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : third_party/imgui/backends/imgui_impl_opengl3.cpp.i

third_party/imgui/backends/imgui_impl_opengl3.s: third_party/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : third_party/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
third_party/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : third_party/imgui/backends/imgui_impl_opengl3.cpp.s

third_party/imgui/backends/imgui_impl_sdl2.o: third_party/imgui/backends/imgui_impl_sdl2.cpp.o
.PHONY : third_party/imgui/backends/imgui_impl_sdl2.o

# target to build an object file
third_party/imgui/backends/imgui_impl_sdl2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/backends/imgui_impl_sdl2.cpp.o
.PHONY : third_party/imgui/backends/imgui_impl_sdl2.cpp.o

third_party/imgui/backends/imgui_impl_sdl2.i: third_party/imgui/backends/imgui_impl_sdl2.cpp.i
.PHONY : third_party/imgui/backends/imgui_impl_sdl2.i

# target to preprocess a source file
third_party/imgui/backends/imgui_impl_sdl2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/backends/imgui_impl_sdl2.cpp.i
.PHONY : third_party/imgui/backends/imgui_impl_sdl2.cpp.i

third_party/imgui/backends/imgui_impl_sdl2.s: third_party/imgui/backends/imgui_impl_sdl2.cpp.s
.PHONY : third_party/imgui/backends/imgui_impl_sdl2.s

# target to generate assembly for a file
third_party/imgui/backends/imgui_impl_sdl2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/backends/imgui_impl_sdl2.cpp.s
.PHONY : third_party/imgui/backends/imgui_impl_sdl2.cpp.s

third_party/imgui/imgui.o: third_party/imgui/imgui.cpp.o
.PHONY : third_party/imgui/imgui.o

# target to build an object file
third_party/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui.cpp.o
.PHONY : third_party/imgui/imgui.cpp.o

third_party/imgui/imgui.i: third_party/imgui/imgui.cpp.i
.PHONY : third_party/imgui/imgui.i

# target to preprocess a source file
third_party/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui.cpp.i
.PHONY : third_party/imgui/imgui.cpp.i

third_party/imgui/imgui.s: third_party/imgui/imgui.cpp.s
.PHONY : third_party/imgui/imgui.s

# target to generate assembly for a file
third_party/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui.cpp.s
.PHONY : third_party/imgui/imgui.cpp.s

third_party/imgui/imgui_demo.o: third_party/imgui/imgui_demo.cpp.o
.PHONY : third_party/imgui/imgui_demo.o

# target to build an object file
third_party/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui_demo.cpp.o
.PHONY : third_party/imgui/imgui_demo.cpp.o

third_party/imgui/imgui_demo.i: third_party/imgui/imgui_demo.cpp.i
.PHONY : third_party/imgui/imgui_demo.i

# target to preprocess a source file
third_party/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui_demo.cpp.i
.PHONY : third_party/imgui/imgui_demo.cpp.i

third_party/imgui/imgui_demo.s: third_party/imgui/imgui_demo.cpp.s
.PHONY : third_party/imgui/imgui_demo.s

# target to generate assembly for a file
third_party/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui_demo.cpp.s
.PHONY : third_party/imgui/imgui_demo.cpp.s

third_party/imgui/imgui_draw.o: third_party/imgui/imgui_draw.cpp.o
.PHONY : third_party/imgui/imgui_draw.o

# target to build an object file
third_party/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui_draw.cpp.o
.PHONY : third_party/imgui/imgui_draw.cpp.o

third_party/imgui/imgui_draw.i: third_party/imgui/imgui_draw.cpp.i
.PHONY : third_party/imgui/imgui_draw.i

# target to preprocess a source file
third_party/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui_draw.cpp.i
.PHONY : third_party/imgui/imgui_draw.cpp.i

third_party/imgui/imgui_draw.s: third_party/imgui/imgui_draw.cpp.s
.PHONY : third_party/imgui/imgui_draw.s

# target to generate assembly for a file
third_party/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui_draw.cpp.s
.PHONY : third_party/imgui/imgui_draw.cpp.s

third_party/imgui/imgui_tables.o: third_party/imgui/imgui_tables.cpp.o
.PHONY : third_party/imgui/imgui_tables.o

# target to build an object file
third_party/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui_tables.cpp.o
.PHONY : third_party/imgui/imgui_tables.cpp.o

third_party/imgui/imgui_tables.i: third_party/imgui/imgui_tables.cpp.i
.PHONY : third_party/imgui/imgui_tables.i

# target to preprocess a source file
third_party/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui_tables.cpp.i
.PHONY : third_party/imgui/imgui_tables.cpp.i

third_party/imgui/imgui_tables.s: third_party/imgui/imgui_tables.cpp.s
.PHONY : third_party/imgui/imgui_tables.s

# target to generate assembly for a file
third_party/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui_tables.cpp.s
.PHONY : third_party/imgui/imgui_tables.cpp.s

third_party/imgui/imgui_widgets.o: third_party/imgui/imgui_widgets.cpp.o
.PHONY : third_party/imgui/imgui_widgets.o

# target to build an object file
third_party/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui_widgets.cpp.o
.PHONY : third_party/imgui/imgui_widgets.cpp.o

third_party/imgui/imgui_widgets.i: third_party/imgui/imgui_widgets.cpp.i
.PHONY : third_party/imgui/imgui_widgets.i

# target to preprocess a source file
third_party/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui_widgets.cpp.i
.PHONY : third_party/imgui/imgui_widgets.cpp.i

third_party/imgui/imgui_widgets.s: third_party/imgui/imgui_widgets.cpp.s
.PHONY : third_party/imgui/imgui_widgets.s

# target to generate assembly for a file
third_party/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui_widgets.cpp.s
.PHONY : third_party/imgui/imgui_widgets.cpp.s

third_party/implot/implot.o: third_party/implot/implot.cpp.o
.PHONY : third_party/implot/implot.o

# target to build an object file
third_party/implot/implot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/implot.dir/build.make CMakeFiles/implot.dir/third_party/implot/implot.cpp.o
.PHONY : third_party/implot/implot.cpp.o

third_party/implot/implot.i: third_party/implot/implot.cpp.i
.PHONY : third_party/implot/implot.i

# target to preprocess a source file
third_party/implot/implot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/implot.dir/build.make CMakeFiles/implot.dir/third_party/implot/implot.cpp.i
.PHONY : third_party/implot/implot.cpp.i

third_party/implot/implot.s: third_party/implot/implot.cpp.s
.PHONY : third_party/implot/implot.s

# target to generate assembly for a file
third_party/implot/implot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/implot.dir/build.make CMakeFiles/implot.dir/third_party/implot/implot.cpp.s
.PHONY : third_party/implot/implot.cpp.s

third_party/implot/implot_demo.o: third_party/implot/implot_demo.cpp.o
.PHONY : third_party/implot/implot_demo.o

# target to build an object file
third_party/implot/implot_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/implot.dir/build.make CMakeFiles/implot.dir/third_party/implot/implot_demo.cpp.o
.PHONY : third_party/implot/implot_demo.cpp.o

third_party/implot/implot_demo.i: third_party/implot/implot_demo.cpp.i
.PHONY : third_party/implot/implot_demo.i

# target to preprocess a source file
third_party/implot/implot_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/implot.dir/build.make CMakeFiles/implot.dir/third_party/implot/implot_demo.cpp.i
.PHONY : third_party/implot/implot_demo.cpp.i

third_party/implot/implot_demo.s: third_party/implot/implot_demo.cpp.s
.PHONY : third_party/implot/implot_demo.s

# target to generate assembly for a file
third_party/implot/implot_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/implot.dir/build.make CMakeFiles/implot.dir/third_party/implot/implot_demo.cpp.s
.PHONY : third_party/implot/implot_demo.cpp.s

third_party/implot/implot_items.o: third_party/implot/implot_items.cpp.o
.PHONY : third_party/implot/implot_items.o

# target to build an object file
third_party/implot/implot_items.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/implot.dir/build.make CMakeFiles/implot.dir/third_party/implot/implot_items.cpp.o
.PHONY : third_party/implot/implot_items.cpp.o

third_party/implot/implot_items.i: third_party/implot/implot_items.cpp.i
.PHONY : third_party/implot/implot_items.i

# target to preprocess a source file
third_party/implot/implot_items.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/implot.dir/build.make CMakeFiles/implot.dir/third_party/implot/implot_items.cpp.i
.PHONY : third_party/implot/implot_items.cpp.i

third_party/implot/implot_items.s: third_party/implot/implot_items.cpp.s
.PHONY : third_party/implot/implot_items.s

# target to generate assembly for a file
third_party/implot/implot_items.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/implot.dir/build.make CMakeFiles/implot.dir/third_party/implot/implot_items.cpp.s
.PHONY : third_party/implot/implot_items.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... imgui"
	@echo "... implot"
	@echo "... main"
	@echo "... src/f.o"
	@echo "... src/f.i"
	@echo "... src/f.s"
	@echo "... src/gui.o"
	@echo "... src/gui.i"
	@echo "... src/gui.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mapper.o"
	@echo "... src/mapper.i"
	@echo "... src/mapper.s"
	@echo "... src/rx.o"
	@echo "... src/rx.i"
	@echo "... src/rx.s"
	@echo "... src/tx.o"
	@echo "... src/tx.i"
	@echo "... src/tx.s"
	@echo "... third_party/imgui/backends/imgui_impl_opengl3.o"
	@echo "... third_party/imgui/backends/imgui_impl_opengl3.i"
	@echo "... third_party/imgui/backends/imgui_impl_opengl3.s"
	@echo "... third_party/imgui/backends/imgui_impl_sdl2.o"
	@echo "... third_party/imgui/backends/imgui_impl_sdl2.i"
	@echo "... third_party/imgui/backends/imgui_impl_sdl2.s"
	@echo "... third_party/imgui/imgui.o"
	@echo "... third_party/imgui/imgui.i"
	@echo "... third_party/imgui/imgui.s"
	@echo "... third_party/imgui/imgui_demo.o"
	@echo "... third_party/imgui/imgui_demo.i"
	@echo "... third_party/imgui/imgui_demo.s"
	@echo "... third_party/imgui/imgui_draw.o"
	@echo "... third_party/imgui/imgui_draw.i"
	@echo "... third_party/imgui/imgui_draw.s"
	@echo "... third_party/imgui/imgui_tables.o"
	@echo "... third_party/imgui/imgui_tables.i"
	@echo "... third_party/imgui/imgui_tables.s"
	@echo "... third_party/imgui/imgui_widgets.o"
	@echo "... third_party/imgui/imgui_widgets.i"
	@echo "... third_party/imgui/imgui_widgets.s"
	@echo "... third_party/implot/implot.o"
	@echo "... third_party/implot/implot.i"
	@echo "... third_party/implot/implot.s"
	@echo "... third_party/implot/implot_demo.o"
	@echo "... third_party/implot/implot_demo.i"
	@echo "... third_party/implot/implot_demo.s"
	@echo "... third_party/implot/implot_items.o"
	@echo "... third_party/implot/implot_items.i"
	@echo "... third_party/implot/implot_items.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

